# Generated by Django 4.1.3 on 2022-11-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(default="", max_length=100, null=True)),
                ("book_author", models.CharField(default="", max_length=50, null=True)),
                ("book_year", models.CharField(default="", max_length=50, null=True)),
                (
                    "book_publisher",
                    models.CharField(default="", max_length=50, null=True),
                ),
                ("book_issues", models.CharField(default="", max_length=50, null=True)),
                (
                    "book_price",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=50, null=True
                    ),
                ),
                (
                    "first_image",
                    models.CharField(default="", max_length=100, null=True),
                ),
                (
                    "second_image",
                    models.CharField(default="", max_length=100, null=True),
                ),
                (
                    "third_image",
                    models.CharField(default="", max_length=100, null=True),
                ),
                (
                    "fourth_image",
                    models.CharField(default="", max_length=100, null=True),
                ),
                (
                    "fifth_image",
                    models.CharField(default="", max_length=100, null=True),
                ),
                (
                    "sixth_image",
                    models.CharField(default="", max_length=100, null=True),
                ),
                (
                    "seventh_image",
                    models.CharField(default="", max_length=100, null=True),
                ),
                (
                    "eighth_image",
                    models.CharField(default="", max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
